version: '3.9'

services:
  site:
    container_name: 'pygreet'
    tty: true
    stdin_open: true
    image: 'python:3.10.7-alpine3.16'
    volumes:
      - '.:/var/www/package/'
    networks:
      - default

networks:
  default: 
    name: 'pygreet_network'
